#################################################
# ConfigMap for index.html for mydata v1
#################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-v1
data:
  index.html: |
    <body bgcolor="green">
      <center>
        <h1><font color="blue">NGINX DEMO</font></h1>
        <h1><font color="blue">V1</font></h1>
      </center>
    </body>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-v2
data:
  index.html: |
    <body bgcolor="red">
      <center>
        <h1><font color="blue">NGINX DEMO</font></h1>
        <h1><font color="blue">V2</font></h1>
      </center>
    </body>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
        listen       8081;
        server_name  localhost;
        #charset koi8-r;
        #access_log  /var/log/nginx/host.access.log  main;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        #error_page  404              /404.html;
        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}
        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}
        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }
---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: demo-v1
      labels:
        app: demo
        version: v1
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: demo
          version: v1
      template:
        metadata:
          labels:
            app: demo
            version: v1
        spec:
          containers:
          - name: nginx
            image: nginx
            ports:
            - containerPort: 8081
            volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: index-html   
            - mountPath: /etc/nginx/conf.d
              readOnly: true
              name: nginx-conf
            - mountPath: /var/log/nginx
              name: log
          volumes:
          - name: nginx-conf
            configMap:
              name: nginx-conf 
              items:
                - key: default.conf
                  path: default.conf
          - name: index-html
            configMap:
              name: demo-v1
          - name: log
            emptyDir: {}
---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: demo-v2
      labels:
        app: demo
        version: v2
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: demo
          version: v2
      template:
        metadata:
          labels:
            app: demo
            version: v2
        spec:
          containers:
          - name: nginx
            image: nginx
            ports:
            - containerPort: 8081
            volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: index-html   
            - mountPath: /etc/nginx/conf.d
              readOnly: true
              name: nginx-conf
            - mountPath: /var/log/nginx
              name: log
          volumes:
          - name: nginx-conf
            configMap:
              name: nginx-conf 
              items:
                - key: default.conf
                  path: default.conf
          - name: index-html
            configMap:
              name: demo-v2
          - name: log
            emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
    name: demo
    labels:
      app: demo
spec:
    ports:
    - name: http
      port: 80
      targetPort: 8081
    selector:
      app: demo
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-gateway
spec:
    selector:
      istio: ingressgateway
    servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: demo
spec:
  hosts:
  - "*"
  gateways:
  - demo-gateway
  http:
  - route:
    - destination:
        host: demo
        subset: v1
      weight: 25
    - destination:
        host: demo
        subnet: v2
      weight: 75
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: demo-rules
spec:
    host: demo
    subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---